### ISSUE TITLE
When a stable version?

### ISSUE THREAD

**Issue by Kappa971** [Kitrinx/SC55_Soundfont#1]
Hello and congratulations for this very ambitious and promising project. Should it reach a "stable", usable version, that would be great! Maybe this could also open the door to a real emulator in the future (like MUNT for the MT-32) and allow everyone to use this synthesizer without spending a lot of money. Anyway, the question is: what are the plans for a usable version release? Thanks :)

**Comment by Kitrinx** [comment]
I got to a point in this project where the soundfont format unfortunately became too limited to really accurately express the sc55, and in order to continue I would have to implement code to pre-render the audio with filtering and pitch modification applied. I think that to continue, it would be better to go one of two ways: Either implement this directly into something that can read the roms and emulate the device, such as MUNT, or create a new version of soundfonts, or a new soundfont format that is able to handle the complexity of the sc-55's method of operation.

MUNT itself is not a bad candidate, because the various envelopes are not as different from the way MT32 works as one might thing, the segue between the two devices is more clear when you dig in. I was contemplating trying to contact someone who is part of that project to see if it's something they might be interested in.

**Comment by Kappa971** [comment]
A MUNT-like emulator for SC-55 would be great, hopefully one day it will come true. Unfortunately I'm not a programmer so I can't help, but I think you should open a new thread in some forum to give it more visibility.

**Comment by Kappa971** [comment]
I have opened an issue in the MUNT repository https://github.com/munt/munt/issues/78, maybe it can be useful to find out if there is actually interest in the project, or maybe not. If there is no interest, I have tried :)

**Comment by Kappa971** [comment]
I want to conclude by saying that we both hope that someone will fork MUNT for the SC-55... But even if there was someone in the world capable of starting such a project, they probably don't have the foundation to start with and they certainly haven't seen the topic of vogons where you have decoded the ROMs... It all started there and finished there, it hasn't been talked about anywhere else and therefore everything is unknown to the vast majority of people. Basically, if no one knows that a small step has been taken with ROM decoding and one of you vogons guys don't "advertise" your progress, I doubt anyone in the future will ever fork MUNT or try to develop an emulator.
This is what I think, nobody forces you to do anything and if you don't want to do it, don't do it, no problem. Thanks for your patience, I will not bother you anymore, regards :)

**Comment by kcgen** [comment]
Well said @Kappa971, I agree. There are so few people with this level of knowledge combined with the time and motivation to progress this aspect of DOS gaming history.

You mentioned "someone in the world", and I fear those are the odds - literally 1 in a billion, that such a project will be both undertaken and produce a result as successful as libmt32emu/munt.

**Comment by Kappa971** [comment]
Sorry @Kitrinx if I still disturb you, this is really the last time. I have an idea floating around in my head but I don't know if it's feasible. This whole project started with Edirol Virtual Sound Canvas. As you well know there is a VST version that can still be used today for example with Falcosoft MIDI Player (both on Windows and Linux via Wine). From what I understand Virtual Sound Canvas is just a synthesizer that reads a "sound bank". So I was wondering if, since no one is able or willing or has time to create an emulator from scratch, it would be possible to create a tool that can convert the ROMs of the SC-55 into a format that Virtual Sound Canvas can understand and reproduce. ? I'm not a programmer so if it were possible I wouldn't even know where to start but I just wanted to know if it's feasible. Thanks again and this is really the last time :)
